"use client"

import { useState } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { FieldGroup, Field, FieldLabel, FieldDescription } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { toast } from "@/components/ui/toast"
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog"
import * as store from "@/lib/skills/store"
import type { Skill } from "@/lib/skills/types"

interface SkillEditorProps {
  skill: Skill | null
  onSave?: (skill: Skill) => void
  onDuplicate?: (id: string) => void
  onDelete?: (id: string) => void
  afterDuplicate?: (newSkill: Skill) => void
}

function sanitizeFilename(name: string): string {
  return name
    .replace(/[<>:"/\\|?*]/g, "_")
    .replace(/\s+/g, "_")
    .slice(0, 100)
}

function exportSkillAsMarkdown(skill: Skill): void {
  const sections: string[] = []

  sections.push(`# ${skill.name}`)
  sections.push("")
  sections.push(skill.description)
  sections.push("")
  sections.push("## Instructions")
  sections.push("")
  sections.push(skill.instructions)
  sections.push("")
  sections.push("## Tools")
  sections.push("")
  if (skill.tools.length > 0) {
    skill.tools.forEach((t) => sections.push(`- ${t}`))
  } else {
    sections.push("- Not specified")
  }
  sections.push("")
  sections.push("---")
  sections.push("")
  sections.push("*Generated by AI Agent Studio*")

  const markdown = sections.join("\n")
  const blob = new Blob([markdown], { type: "text/markdown" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `${sanitizeFilename(skill.name)}.md`
  a.click()
  URL.revokeObjectURL(url)
}

export function SkillEditor({
  skill,
  onSave,
  onDuplicate,
  onDelete,
  afterDuplicate,
}: SkillEditorProps) {
  const router = useRouter()
  const [name, setName] = useState(skill?.name ?? "")
  const [description, setDescription] = useState(skill?.description ?? "")
  const [instructions, setInstructions] = useState(skill?.instructions ?? "")
  const [toolsRaw, setToolsRaw] = useState(skill?.tools.join(", ") ?? "")

  function handleSave() {
    if (!skill) return

    try {
      const tools = toolsRaw
        .split(",")
        .map((t) => t.trim())
        .filter((t) => t.length > 0)
      const updated = store.update(skill.id, {
        name,
        description,
        instructions,
        tools,
      })
      if (updated) {
        toast.add({ title: "Skill saved", type: "success" })
        onSave?.(updated)
      } else {
        toast.add({ title: "Failed to save", type: "error" })
      }
    } catch {
      toast.add({ title: "Failed to save", type: "error" })
    }
  }

  function handleDuplicate() {
    if (!skill) return

    try {
      const cloned = store.duplicate(skill.id)
      if (cloned) {
        toast.add({ title: "Skill duplicated", type: "success" })
        onDuplicate?.(skill.id)
        afterDuplicate?.(cloned)
        router.push(`/skills/${cloned.id}`)
      } else {
        toast.add({ title: "Failed to duplicate", type: "error" })
      }
    } catch {
      toast.add({ title: "Failed to duplicate", type: "error" })
    }
  }

  function handleDelete() {
    if (!skill) return

    try {
      const removed = store.remove(skill.id)
      if (removed) {
        toast.add({ title: "Skill deleted", type: "success" })
        onDelete?.(skill.id)
        router.push("/skills")
      } else {
        toast.add({ title: "Failed to delete", type: "error" })
      }
    } catch {
      toast.add({ title: "Failed to delete", type: "error" })
    }
  }

  function handleExport() {
    if (!skill) return

    try {
      exportSkillAsMarkdown(skill)
      toast.add({ title: "Skill exported as Markdown", type: "success" })
    } catch {
      toast.add({ title: "Failed to export", type: "error" })
    }
  }

  if (!skill) {
    return (
      <div className="flex flex-col items-center gap-4">
        <p className="text-muted-foreground">Skill not found</p>
        <Button variant="outline" render={<Link href="/skills" />} nativeButton={false}>
          Back to List
        </Button>
      </div>
    )
  }

  return (
    <div className="flex flex-col gap-6">
      <FieldGroup>
        <Field>
          <FieldLabel htmlFor="skill-name">Name</FieldLabel>
          <Input
            id="skill-name"
            value={name}
            onChange={(e) => setName(e.target.value)}
          />
        </Field>
        <Field>
          <FieldLabel htmlFor="skill-description">Description</FieldLabel>
          <Textarea
            id="skill-description"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
          />
        </Field>
        <Field>
          <FieldLabel htmlFor="skill-instructions">Instructions</FieldLabel>
          <Textarea
            id="skill-instructions"
            value={instructions}
            onChange={(e) => setInstructions(e.target.value)}
            rows={6}
            className="font-mono"
          />
        </Field>
        <Field>
          <FieldLabel htmlFor="skill-tools">Tools</FieldLabel>
          <Textarea
            id="skill-tools"
            value={toolsRaw}
            onChange={(e) => setToolsRaw(e.target.value)}
            rows={3}
            placeholder="GitHub, Linear, Slack"
          />
          <FieldDescription>Comma-separated tool names</FieldDescription>
        </Field>
      </FieldGroup>

      <div className="rounded-md border p-4 flex flex-col gap-4">
        <section className="flex flex-col gap-1">
          <h4 className="text-sm font-medium text-muted-foreground">DESCRIPTION</h4>
          <p>{skill.description || "—"}</p>
        </section>
        <section className="flex flex-col gap-1">
          <h4 className="text-sm font-medium text-muted-foreground">INSTRUCTIONS</h4>
          <p className="whitespace-pre-wrap text-sm">{skill.instructions || "—"}</p>
        </section>
        <section className="flex flex-col gap-1">
          <h4 className="text-sm font-medium text-muted-foreground">TOOLS</h4>
          <div className="flex flex-wrap gap-1">
            {skill.tools.length > 0 ? (
              skill.tools.map((tool) => (
                <span
                  key={tool}
                  className="rounded-md bg-secondary px-2 py-0.5 text-xs"
                >
                  {tool}
                </span>
              ))
            ) : (
              <p className="text-sm text-muted-foreground">Not specified</p>
            )}
          </div>
        </section>
      </div>

      <div className="flex flex-col gap-3 sm:flex-row">
        <Button onClick={handleSave}>Save Changes</Button>
        <Button variant="outline" onClick={handleDuplicate}>
          Duplicate
        </Button>
        <AlertDialog>
          <AlertDialogTrigger render={<Button variant="destructive" />}>
            Delete
          </AlertDialogTrigger>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Delete skill</AlertDialogTitle>
              <AlertDialogDescription>
                Are you sure you want to delete &quot;{skill.name}&quot;? This action cannot be undone.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancel</AlertDialogCancel>
              <AlertDialogAction onClick={handleDelete}>
                Delete
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
        <Button variant="outline" onClick={handleExport}>
          Export as Markdown
        </Button>
        <Button variant="outline" render={<Link href="/skills" />} nativeButton={false}>
          Back to List
        </Button>
      </div>
    </div>
  )
}